.TH "UDPSocket.h" 3 "Tue Nov 15 2016" "Zamasu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UDPSocket.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'UDPMessage\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZamasu::UDPSocket\fP"
.br
.RI "\fIBasic class to send and receive std::string's with UDP protocol\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZamasu\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zamasu from the source code\&.
