.TH "Utils.h" 3 "Tue Nov 15 2016" "Zamasu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZamasu\fP"
.br
.ti -1c
.RI " \fBZamasu::Utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBZamasu::Utils::split\fP (std::string str, std::string c)"
.br
.ti -1c
.RI "size_t \fBZamasu::Utils::char_count\fP (std::string str, char c)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zamasu from the source code\&.
