.TH "Zamasu::Message" 3 "Tue Nov 15 2016" "Zamasu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zamasu::Message \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UDPMessage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessage\fP (std::string host, std::string message)"
.br
.ti -1c
.RI "std::string \fBget_host\fP ()"
.br
.ti -1c
.RI "std::string \fBget_message\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Message::Message (std::string host, std::string message)"

.SH "Member Function Documentation"
.PP 
.SS "std::string Message::get_host ()"

.SS "std::string Message::get_message ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zamasu from the source code\&.
