.TH "Zamasu::Utils" 3 "Tue Nov 15 2016" "Zamasu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zamasu::Utils \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBsplit\fP (std::string str, std::string c)"
.br
.ti -1c
.RI "size_t \fBchar_count\fP (std::string str, char c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t Zamasu::Utils::char_count (std::string str, char c)"

.SS "std::vector< std::string > Zamasu::Utils::split (std::string str, std::string c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Zamasu from the source code\&.
