.TH "ZamasuClient.h" 3 "Tue Nov 15 2016" "Zamasu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZamasuClient.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Attribute\&.h'\fP
.br
\fC#include 'UDPSocket\&.h'\fP
.br
\fC#include 'UDPMessage\&.h'\fP
.br
\fC#include 'Utils\&.h'\fP
.br
\fC#include <thread>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZamasu::Client\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZamasu\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zamasu from the source code\&.
