.TH "ZamasuServer.cpp" 3 "Tue Nov 15 2016" "Zamasu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZamasuServer.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ZamasuServer\&.h'\fP
.br
\fC#include 'UDPMessage\&.h'\fP
.br
\fC#include 'Utils\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< std::string, \fBAttribute\fP * >::iterator \fBattr_it\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBClientInfo\fP * >::iterator \fBclient_it\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::map<std::string, \fBAttribute\fP*>::iterator \fBattr_it\fP"

.SS "typedef std::vector<\fBClientInfo\fP*>::iterator \fBclient_it\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Zamasu from the source code\&.
