.TH "Zamasu" 3 "Tue Nov 15 2016" "Zamasu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zamasu \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUtils\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAttribute\fP"
.br
.ti -1c
.RI "class \fBClient\fP"
.br
.ti -1c
.RI "class \fBClientInfo\fP"
.br
.RI "\fIBasic Class with common attributes for Clients that will be communicating with \fBServer\fP instances\&. \fP"
.ti -1c
.RI "class \fBMessage\fP"
.br
.ti -1c
.RI "class \fBServer\fP"
.br
.ti -1c
.RI "class \fBUDPSocket\fP"
.br
.RI "\fIBasic class to send and receive std::string's with UDP protocol\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zamasu from the source code\&.
